// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GameStepMini: typeof import('./../src/components/GameStepMini.vue')['default']
    MainStep: typeof import('./../src/components/MainStep.vue')['default']
    Map: typeof import('./../src/components/Map.vue')['default']
    MultiBox: typeof import('./../src/components/MultiBox.vue')['default']
    PlayVideo: typeof import('./../src/components/PlayVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleBox: typeof import('./../src/components/SingleBox.vue')['default']
    TextDes: typeof import('./../src/components/TextDes.vue')['default']
    TitleBar: typeof import('./../src/components/TitleBar/index.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
  }
}
